apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-proto
  labels:
    app: postgres-proto
    role: db
spec:
  selector:
    matchLabels:
      app: postgres-proto
      role: db
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: postgres-proto
        role: db
    spec:
      containers:
        - name: postgres-proto
          image: postgres:15.17-trixie
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.POSTGRES_PASSWORD }}"
            - name: PGUSER
              value: "{{ .Values.PGUSER }}"