apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
spec:
  type: NodePort
  selector:
    app: postgres-proto
    role: db
  ports:
    - port: {{ .Values.svcPort }}
      targetPort: {{ .Values.containerPort }}
