import type { Metadata } from "next";
import "./globals.css";
import { fenixFont } from "@/app/fonts/types";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={fenixFont.className}> {children} </body>
        </html>
    );
}
