import type { Metadata } from "next";
import localFont from "next/font/local";
// import { Fenix } from "next/font/google";
import "./globals.css";

const fontFenix = localFont({
    src: "./fonts/Fenix/Fenix-Regular.ttf",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={fontFenix.className}> {children} </body>
        </html>
    );
}
