apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: registry-data
  hostPath:
    path: /mnt/registry-data
