{{- range .Values.global.postgresql }}
{{- if .enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-{{ .name }}
spec:
  selector:
    app: postgresql-{{ .name }}
    role: primary
  ports:
    - port: 5432
      targetPort: 5432
{{- end }}
{{- end }}