{{- range .Values.global.postgresql }}
{{- if .enabled }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-{{ .name }}
  labels:
    app: postgresql-{{ .name }}
    role: primary
spec:
  serviceName: postgresql-{{ .name }}
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-{{ .name }}
      role: primary
  template:
    metadata:
      labels:
        app: postgresql-{{ .name }}
        role: primary
    spec:
      containers:
        - name: postgresql
          image: postgres:14.22
          env:
            - name: POSTGRES_USER
              value: {{ .username | quote }}

            - name: POSTGRES_PASSWORD
              value: {{ .password | quote }}

            - name: POSTGRES_DB
              value: {{ .database | quote }}
          volumeMounts:
            - name: postgresql-{{ .name }}
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgresql-{{ .name }}
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: postgresql-data-{{ .name }}
        volumeName: postgresql-{{ .name }}
        resources:
          requests:
            storage: {{ .storage }}
{{- end }}
{{- end }}
