apiVersion: v1
kind: Service
metadata:
  name: cluster-registry-svc
spec:
  type: NodePort
  selector:
    app: cluster-registry
  ports:
    - port: {{ .Values.svcPort }}
      targetPort: {{ .Values.containerPort }}
