apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${PV_NAME}
spec:
  capacity:
    storage: ${STORAGE_CAPACITY}
  accessModes:
    - ReadWriteOnce
  storageClassName: ${STORAGE_CLASS}
  hostPath:
    path: ${HOST_PATH}
