apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "node-app.fullname" . }}
spec:
  capacity:
    storage: {{ .Values.pv.storageCapacity }}
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ include "node-app.fullname" . }}-data
  hostPath:
    path: {{ .Values.pv.hostPath }}