apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "node-app.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.storageRequest }}
  storageClassName: {{ include "node-app.fullname" . }}-data