fullnameOverride: "bff-users"

replicaCount: 1

image:
  repository: node
  tag: 24.15.0-bookworm
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent

container:
  command: ["sh", "-c"]
  args:
    [
      "cd /app && npm install && mkdir -p node_modules/@app && ln -sf /contracts node_modules/@app/contracts && NODE_OPTIONS=--preserve-symlinks npm run dev",
    ]
  mountPath: /app

volumes:
  - name: contracts
    hostPath:
      path: /mnt/contracts

volumeMounts:
  - name: contracts
    mountPath: /contracts

# Persistent Volume
pv:
  hostPath: /mnt/apps/bff/users/src
  storageCapacity: 10Gi

# Persistent Volume Claim
pvc:
  storageRequest: 10Gi

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 80
