apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name }}-postgres
spec:
  selector:
    app: {{ .Values.db.name }}-postgres
    role: primary
  ports:
    - port: 5432
      targetPort: 5432