apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-dev
  template:
    metadata:
      labels:
        app: frontend-dev
    spec:
      containers:
        - name: frontend-dev
          image: node:24.15.0-bookworm
          ports:
            - containerPort: 3000 # NextJS
            - containerPort: 8080 # Storybook
          command: ["sh", "-c"]
          args:
            - cd /app && npm install && mkdir -p node_modules/@app && ln -sf /contracts node_modules/@app/contracts && NODE_OPTIONS=--preserve-symlinks npx concurrently "npm run dev" "npm run storybook"
