import "./globals.css";
import { fenixFont } from "@/app/fonts/types";
import IconButton from "@/ui/components/Buttons/IconButton/IconButton";
import { faCircleHalfStroke } from "@fortawesome/free-solid-svg-icons";
import Navbar from "@/features/navigation/components/Navbar/Navbar";
import * as Modal from "@/ui/components/Overlays/Modal/modal";
import ThemePicker from "@/ui/components/Preferences/ThemePicker/ThemePicker";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config as fontAwesomeConfig } from "@fortawesome/fontawesome-svg-core";

fontAwesomeConfig.autoAddCss = false;

/*
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
*/

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={fenixFont.className}>
                <Navbar />
                <main
                    style={{
                        position: "relative",
                        // minHeight: "100%",
                    }}
                >
                    {children}
                </main>

                <Modal.Root>
                    <Modal.Trigger
                        triggerValue={true}
                        asChild
                    >
                        <IconButton
                            style={{
                                position: "fixed",
                                bottom: "10px",
                                right: "10px",
                            }}
                            icon={faCircleHalfStroke}
                            width="50px"
                            height="50px"
                            iconSize="25px"
                        />
                    </Modal.Trigger>
                    <Modal.Content
                        backgroundBlurOpacity="0"
                        backgroundBlurRadius="0"
                    >
                        {/* <div
                            style={{
                                backgroundColor: "var(--primary)",
                                outlineWidth: "2px",
                                outlineStyle: "solid",
                                outlineColor: "var(--tertiary)",
                                backdropFilter: "blur(1px)",
                            }}
                        > */}
                        <ThemePicker />
                        {/* </div> */}
                    </Modal.Content>
                </Modal.Root>
            </body>
        </html>
    );
}
