import "./globals.css";
import { fenixFont } from "@/app/fonts/fonts";
import Navbar from "@/features/navigation/components/Navbar/Navbar";
import ThemePicker from "@/features/preferences/components/ThemePicker/ThemePicker";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config as fontAwesomeConfig } from "@fortawesome/fontawesome-svg-core";

fontAwesomeConfig.autoAddCss = false;

/*
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
*/

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const isSignedIn = true;

    return (
        <html lang="en">
            <body
                className={fenixFont.className}
                style={{
                    display: "flex",
                    flexDirection: "column",
                    height: "100vh",
                }}
            >
                <Navbar />
                <main
                    style={{
                        display: "flex",
                        flexGrow: 1,
                        minHeight: 0,
                    }}
                >
                    {children}
                </main>
                <ThemePicker />
            </body>
        </html>
    );
}
